apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myjavaapp
      version: 2.7.02
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.7.02
    spec:
      containers:
      - name: myjavaapp-container
        image: ravidevops26/k8sapp:1
        ports:
        - containerPort: 8080
